# Generated by Django 4.0.5 on 2022-06-29 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Google_Sheets_Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(unique=True)),
                ('order_number', models.IntegerField()),
                ('dollar_price', models.IntegerField()),
                ('delivery_time', models.DateField()),
                ('rub_price', models.IntegerField()),
            ],
        ),
    ]
