# Generated by Django 4.0.5 on 2022-06-29 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('google_sheets_service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='google_sheets_table',
            name='number',
            field=models.IntegerField(),
        ),
    ]
