# Generated by Django 4.0.5 on 2022-06-29 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('google_sheets_service', '0002_alter_google_sheets_table_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='google_sheets_table',
            name='id',
        ),
        migrations.AlterField(
            model_name='google_sheets_table',
            name='number',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
